"""connected User and League classes

Revision ID: cd373514dee8
Revises: dd51bd181bbf
Create Date: 2018-08-06 09:26:06.534687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd373514dee8'
down_revision = 'dd51bd181bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=False)
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('commissioner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commissioner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_name'), 'league', ['name'], unique=True)
    op.create_index(op.f('ix_league_size'), 'league', ['size'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memberships')
    op.drop_index(op.f('ix_league_size'), table_name='league')
    op.drop_index(op.f('ix_league_name'), table_name='league')
    op.drop_table('league')
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
